name       : systemsettings
version    : 5.27.4
release    : 87
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.4/systemsettings-5.27.4.tar.xz : 6d39a082e9532f0f41295afd20c3c4d7075d8ecd829529537e201a6a76664d07
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2-only
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
optimize   : lto
builddeps  :
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kactivities-devel
    - kactivities-stats-devel
    - kio-devel
    - kiconthemes-devel
    - kirigami2-devel
    - kitemmodels-devel
    - kguiaddons-devel
    - knotifications-devel
    - krunner-devel
    - plasma-workspace-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    rm -rf $installdir/usr/share/doc
