name       : systemsettings
version    : 5.16.2
release    : 36
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.2/systemsettings-5.16.2.tar.xz : 12c221a905b1c4e751e6b3c346f652ad10297f537fc9934955db65d6788e59d5
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - khtml-devel
    - kiconthemes-devel
    - kirigami2-devel
    - kwindowsystem-devel
    - plasma-workspace-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
