name       : systemsettings
version    : 5.19.2
release    : 51
source     :
    - https://cdn.download.kde.org/stable/plasma/5.19.2/systemsettings-5.19.2.tar.xz : f761b844368573414a7e933020ca8a6b4af1d96dd00cf4653fe525f324c50787
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kiconthemes-devel
    - kirigami2-devel
    - kitemmodels-devel
    - kguiaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - plasma-workspace-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
