name       : systemsettings
version    : 5.15.5
release    : 33
source     :
    - https://download.kde.org/stable/plasma/5.15.5/systemsettings-5.15.5.tar.xz : a29227329f8ddd2db2ba8aafb3eb5f2b09d01e3a6f761d291afba95935ceb93a
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - khtml-devel
    - kiconthemes-devel
    - kirigami2-devel
    - kwindowsystem-devel
    - plasma-workspace-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
