name       : systemsettings
version    : 5.11.4
release    : 8
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.4/systemsettings-5.11.4.tar.xz : 63d12c2a9f53d7cd5ebb9ab1f251594bb44f69013baef3ea176cc1028a2ba5c8
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfig-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kirigami2-devel
    - kpackage-devel
    - kservice-devel
    - kwindowsystem-devel
    - kxmlgui-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
