name       : systemsettings
version    : 5.16.5
release    : 39
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.5/systemsettings-5.16.5.tar.xz : 57944cf3f566cf5e25d5859f5716b2ad5dbd87de259f8d77efdfdd50a16fe1ec
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - khtml-devel
    - kiconthemes-devel
    - kirigami2-devel
    - kwindowsystem-devel
    - plasma-workspace-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
