name       : systemsettings
version    : 5.25.3
release    : 83
source     :
    - https://cdn.download.kde.org/stable/plasma/5.25.3/systemsettings-5.25.3.tar.xz : 99d0ec23f63934c93ce3de99e61bd21f9552b615eaebdcb4e36c808b43c9c402
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2-only
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
optimize   : lto
builddeps  :
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kactivities-devel
    - kactivities-stats-devel
    - kio-devel
    - kiconthemes-devel
    - kirigami2-devel
    - kitemmodels-devel
    - kguiaddons-devel
    - knotifications-devel
    - krunner-devel
    - plasma-workspace-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    rm -rf $installdir/usr/share/doc
