name       : systemsettings
version    : 5.12.2
release    : 12
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.2/systemsettings-5.12.2.tar.xz : 965cab685c5c37fcbe295743fff4b4f0e7c7757cfac41bcd2bf15b769bef8e19
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfig-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kirigami2-devel
    - kpackage-devel
    - kservice-devel
    - kwindowsystem-devel
    - kxmlgui-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
