name       : systemsettings
version    : 5.20.5
release    : 60
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.5/systemsettings-5.20.5.tar.xz : b2e03bc39a1c7f4e298c8c196a22e22291a5b71ecd972234c6a47d9b284c32ac
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kiconthemes-devel
    - kirigami2-devel
    - kitemmodels-devel
    - kguiaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - plasma-workspace-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    rm -rf $installdir/usr/share/doc
