name       : systemsettings
version    : 5.9.5
release    : 1
source     :
    - https://download.kde.org/stable/plasma/5.9.5/systemsettings-5.9.5.tar.xz : e93d5876a4bc6d9fc76d9e7f4db10d562693ba2f881aa8a95b62837a21f2e875
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfig-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kservice-devel
    - kwindowsystem-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
