name       : systemsettings
version    : 5.17.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.0/systemsettings-5.17.0.tar.xz : 7b3d93bd3cd4c33b878aabff4bd9c8134ca7395a0290e59260464cf5d69f17f3
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kiconthemes-devel
    - kirigami2-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - plasma-workspace-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
