name       : systemsettings
version    : 5.11.0
release    : 4
source     :
    - https://download.kde.org/stable/plasma/5.11.0/systemsettings-5.11.0.tar.xz : 2b7878c16d30ffb7915e9db58eedb18e5460659f668ab3945afdd675894cacf1
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfig-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kirigami2-devel
    - kpackage-devel
    - kservice-devel
    - kwindowsystem-devel
    - kxmlgui-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
