name       : systemsettings
version    : 5.24.2
release    : 78
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.2/systemsettings-5.24.2.tar.xz : b31e3bbd0ed6c69718341e7290f8a8888e972ca3c1eae10f2a5da912b17d2e5c
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2-only
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
optimize   : lto
builddeps  :
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kactivities-devel
    - kactivities-stats-devel
    - kio-devel
    - kiconthemes-devel
    - kirigami2-devel
    - kitemmodels-devel
    - kguiaddons-devel
    - knotifications-devel
    - krunner-devel
    - plasma-workspace-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    rm -rf $installdir/usr/share/doc
