name       : systemsettings
version    : 5.16.1
release    : 35
source     :
    - https://download.kde.org/stable/plasma/5.16.1/systemsettings-5.16.1.tar.xz : 8cf55e4734f1106719d763d1711fa88d2e4dd60bb6e7d85d00261cc2065b0a70
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - khtml-devel
    - kiconthemes-devel
    - kirigami2-devel
    - kwindowsystem-devel
    - plasma-workspace-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
