name       : systemsettings
version    : 5.15.4
release    : 32
source     :
    - https://cdn.download.kde.org/stable/plasma/5.15.4/systemsettings-5.15.4.tar.xz : 2cff11f842266296192381a214df6fd55debfd444b754b6dec80f70a3154defb
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
builddeps  :
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - khtml-devel
    - kiconthemes-devel
    - kirigami2-devel
    - kwindowsystem-devel
    - plasma-workspace-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
