name       : systemsettings
version    : 5.27.5
release    : 89
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.5/systemsettings-5.27.5.tar.xz : d5454eb0aaba331e724bd91650474bbe1658f26fcc543ab7804186bccf50b4db
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GFDL-1.2-only
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
optimize   : lto
builddeps  :
    - kcmutils-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - kactivities-devel
    - kactivities-stats-devel
    - kio-devel
    - kiconthemes-devel
    - kirigami2-devel
    - kitemmodels-devel
    - kguiaddons-devel
    - knotifications-devel
    - krunner-devel
    - plasma-workspace-devel
rundeps    :
    - flatpak-kcm
    - kirigami2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
    rm -rf $installdir/usr/share/doc
