name       : systemsettings
version    : 5.12.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/plasma/5.12.0/systemsettings-5.12.0.tar.xz : 0b6d4bca5a09b2039d52ebad1bb5f8de71698b3e3fdf6f7ad9cc5688fe8ab144
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfig-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kirigami2-devel
    - kpackage-devel
    - kservice-devel
    - kwindowsystem-devel
    - kxmlgui-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
