name       : systemsettings
version    : 5.13.4
release    : 20
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.4/systemsettings-5.13.4.tar.xz : 04a3f95421bb2e271ab7301cd5c7aeafe54a943792151c35366745f0d534ccfc
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : System settings utility for Plasma
description: |
    This is a collection of standard plugin interfaces to System Settings.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libKActivities)
    - pkgconfig(libKActivitiesStats)
    - pkgconfig(Qt5Quick)
    - extra-cmake-modules
    - kcmutils-devel
    - kconfig-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kirigami2-devel
    - kpackage-devel
    - kservice-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - plasma-workspace-devel
rundeps    :
    - kirigami2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
